### ISSUE TITLE
Settings Options

### ISSUE THREAD

**Issue by jpham93** [jpham93/ionic-pomodoro#4]
Create a new modal for settings that dynamically changes the Homepage UI.

**TODO:**
- [x] In setting options in client application User's should be able to pick:
    - [x] Background image
    - [x] Color scheme 
    - [x] Alarm sound
---
- [x] localStorage or IonicStorage should contain menu options. 
    - On app initiation, local storage should add default options.
    - Setting options should reflect these global variables.
---
- [x] Background image changes should show in main. Consider how to pass JS variable to the Sass file.
- [x] Alarm sound should change when selected in settings.
- [x] Color scheme should change when selected on the home page.
---
- [x] Create a service for pushing and fetching data form Ionic Storage.
- [x] Create an Observable for loading async fetching completely.
- [x] Initiate Storage when creating service in the initial App launch.

**Comment by jpham93** [comment]
closes #7
